name: Sync Mirror

on:
  schedule:
    - cron: '0 * * * *' # Sync every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions-bot@users.noreply.github.com"

      - name: Fetch upstream changes
        run: |
          git remote add upstream https://vcs.firestormviewer.org/phoenix-firestorm
          git fetch upstream --prune --tags

      - name: Push changes to mirror
        run: |
          git push origin --all
          git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
